### ISSUE TITLE
Broken meta for life.eustathius.theopiste.02

### ISSUE THREAD

**Issue by amir-zeldes** [CopticScriptorium/corpora#100]
Metadata seems to be broken in GD just for part 2, which prevents the page from loading on CTS:

https://data.copticscriptorium.org/texts/lifeeustathiustheopiste/history-of-eustathius-and-theopiste-part-2/norm

I can patch the release and update it, but @ctschroeder can you take a look if something special is going on/needed to be checked for part 2 of this corpus?

**Comment by ctschroeder** [comment]
It looks like this document was published before it was ready, but in our [publication thread](https://github.com/CopticScriptorium/budge-dev/issues/12) we clearly seem to have gone through our checklist thoroughly. Is it possible the document was overwritten with an older version? I'm not seeing anything in the commit history to suggest that, though. It's very strange. It looks like this is my doing (or not doing) as well. So odd.

It will take me a minute to deal with this -- a TON of metadata is missing, including the URN. 

I think it is not the end of the world if this is broken until our next release in April but if you want to do a mini release of this corpora, I'll let you know when I'm done.

**Comment by amir-zeldes** [comment]
Yes, that is indeed strange... But I don't think it's so urgent, we can just roll it out with the rest of the release and not complicate version numbers or anything. Let's just add it to the roster (and in fact I re-release any corpus with 'review' status documents anyway). Thanks!

**Comment by ctschroeder** [comment]
this is done
