### ISSUE TITLE
URN for gold Ruth is the same as big OT Ruth

### ISSUE THREAD

**Issue by amir-zeldes** [CopticScriptorium/corpora#103]
This yields a URN error in the mapper:

urn:cts:copticLit:ot.ruth.coptot:2

The reason seems to be that gold Ruth and auto OT Ruth have the same URN. This is handled differently for NT, e.g. gold Mark has URNs with sahidica_ed, while auto NT Mark has just sahidica. Should we follow the same convention for Ruth?

**Comment by ctschroeder** [comment]
Ohhh kay. We really are supposed to be using _ed for any edition we take and modify in any way (which is basically all of the republished/repurposed ones), but I got inconsistent during Covid for obvious reasons.  I guess we could use _ed for the gold Ruth? I don't think I have a better solution.

**Comment by amir-zeldes** [comment]
Sure, I think that makes sense. We should just add a note to the release issue so we don't forget to do this.

**Comment by amir-zeldes** [comment]
Added

**Comment by ctschroeder** [comment]
all urns changed to edition namespace = coptot_ed
all vid_ns also changed

I did NOT change the title for the filenames or anything else that might overlap

**Comment by amir-zeldes** [comment]
Thanks!
