### ISSUE TITLE
URNs for Bible books without edition only fetch Sahidic

### ISSUE THREAD

**Issue by amir-zeldes** [CopticScriptorium/corpora#113]
Currently Bohairic URNs are like:

`urn:cts:copticLit:nt.1cor.bohairic_ed`

This leads to the expectation that this will fetch both Sahidic and Bohairic 1Cor:

`urn:cts:copticLit:nt.1cor`

But in fact, this fetches only the Sahidic:

https://data.copticscriptorium.org/urn:cts:copticLit:nt.1cor

The expected behavior would be to fetch both

**Comment by ctschroeder** [comment]
I checked some other corpora. FYI others seem to work, such as [urn:cts:copticLit:johannes.canons](https://data.copticscriptorium.org/urn:cts:copticLit:johannes.canons) produces all canons regardless of edition/ms

**Comment by amir-zeldes** [comment]
Oh, that was helpful thanks, I figured it out (mapping was wrong in gh_ingest/mappings.tab). Should work now!

**Comment by ctschroeder** [comment]
Excellent
