### ISSUE TITLE
wonky data.copticscriptorium.org visualizations

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/corpora#16]
I noticed some wonky stuff when I was trying to show material to someone who stopped by my office with an interest in Coptic John.  The chapter view viz in ANNIS is linked to the dictionary.  The chapter view viz in our site repository for reading was not linked.
https://corpling.uis.georgetown.edu/annis/?id=684bbcd6-5b3d-4718-8b45-ba5f4a2e22f9
vs
http://data.copticscriptorium.org/texts/new-testament/john_1/sahidica

Also the urns are wrong for John.  They're all directing to the first letter of John (1John) instead of John.  I believe we autogenerated the URNs.  Something went weird. 

Any way we can prioritize this, since it's a user issue?  Please let me know if there's anything I can do (e.g., edit the URNs manually, re-ingest, etc.).  Thanks.

**Comment by amir-zeldes** [comment]
OK, I see the problem - the URN should be urn:cts:copticLit:nt.john.sahidica, with no numbers, right?

**Comment by amir-zeldes** [comment]
@ctschroeder corpus is now ready to do this, if you say go to `urn:cts:copticLit:nt.john.sahidica`. Then we'd just need to re-ingest.

**Comment by ctschroeder** [comment]
Yes 1john to john. Thanks!

Sent from my iPhone

**Comment by amir-zeldes** [comment]
OK, reimport complete – if this looks good, feel free to re-ingest for data.*
