### ISSUE TITLE
corpus metadata in CS Gitdox

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/corpora#17]
needed for Spring 2018 publication

**Comment by ctschroeder** [comment]
https://github.com/cligu/gitdox/issues/56

**Comment by ctschroeder** [comment]
Is there a way to import corpus data or should we manually add? I'm looking at pseudo-theophilus, and I don't see corpus metadata, yet. Wanted to check before manually adding. Thanks!!!

**Comment by amir-zeldes** [comment]
No, there isn't a batch import option at the moment... It would probably take as long to key these for existing corpora as it would to write an import script, so maybe it's best to just enter them as we re-publish each corpus (they need to be checked then anyway, and fields are not many for the corpus level)

**Comment by ctschroeder** [comment]
Gotcha. Thanks.

**Comment by ctschroeder** [comment]
How is this going? Thx.

**Comment by ctschroeder** [comment]
How is this going @eplatte ?

**Comment by eplatte** [comment]
Corpus metadata added to GitDox in Feb.
