### ISSUE TITLE
language/languages in medatada

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/corpora#18]
Field name should be language.
check 
a22.YB307-20
a22.YA421-428
Mark_01
to_aphthonia
XL93-94 (abraham)
XJ33-34 (eagerness)
cpr.2.237 papyri

**Comment by ctschroeder** [comment]
are we done with this work? thx

**Comment by ctschroeder** [comment]
How is this going @eplatte ?

**Comment by eplatte** [comment]
All done! Closing now.
