### ISSUE TITLE
Coptic OT for fall 2018 publication

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/corpora#21]
This is the publication thread for the new Coptic OT "base text" donated by the Coptic OT project in Goettingen.  @ctschroeder & @amir-zeldes are coordinating on the following items:

- [x] aligning LXX english translation with Coptic text
- [x] verse cts urns following pattern of urn:cts:copticLit:ot.gen.coptot:1.1
- [x] document cts urn following pattern of urn:cts:copticLit:ot.gen.coptot:1 (no initial zeros in the urns per Bridget Almas; book abbreviations follow the [SBL abbreviations](https://www.nashotah.edu/sites/default/files/Biblical%20Abbreviations.pdf) )
- [x] version #s for tools
- [x] adding a note about automated processing + automated transl alignment (so alignment may be off in places)
- [ ] add a redirect page for the previous edition or add info on how to access it to the 404 page
Please add anything else to the checklist here.

**Comment by ctschroeder** [comment]
csv file mapping LXX translation to CoptOT is in the bible-dev repo. Pls see commit note.  Thanks!

**Comment by ctschroeder** [comment]
New files for mapping translations are in the [bible-dev repo](https://github.com/CopticScriptorium/bible-dev/tree/master/OT) @amir-zeldes.  Mapping based on the CoptOT September 2018 text data. 
1) csv file mapping most of the KNOWN verses where the LXX translation versification does not align with the CoptOT data versification.  Mapping does not map all books/chapters/verses; it only maps known problems. This file is NOT ready to go.  Please read...
2) my notes file.  This has all my notes on how I found misalignments, what's going on in each book with a known misalignment, and a list of books/chapters with problems for which I have not yet figured out the solution.  We may need to go over this material in person.

**Comment by ctschroeder** [comment]
See mapping file + notes in the OT folder.  Decision was to null out English translation where it was difficult to match up the Coptic data with the Brenton translation.  We may hire a student to work on that this fall.

**Comment by ctschroeder** [comment]
From email (so I don't lose this thread): items still under discussion

Data
- [ ] corpus name (coptot.ot? sahidic.ot?)
- [ ] "verse" layer is a number, verse@vname forlayer with bookname ch:v
- [ ] verse level urns (document urn + . verse number)? 

Metadata corpus AND document levels
- [ ] project: add KELLIA
- [ ] license: add 4.0
- [ ] translation field: add year of publication
- [ ] translation or source: add link to translation source (since our source for the translation is not the book itself, it's some third party who posted it online).  Either in the translation field or source field?

Metadata Corpus level
- [ ] do we want add the bound-group tool version number to the metadata?

Metadata Document level
- [ ] add parsing, segmentation, tagging fields (set to automatic)

**Comment by amir-zeldes** [comment]
Should be good to go, test version behind login on ANNIS

**Comment by ctschroeder** [comment]
This looks really good.  There are some odd “book names” that I didn’t notice before, like “epistle of Jeremiah” which isn’t an epistle —it’s the prophetic book Jeremiah, right?— but I assume that comes from the Copt OT data?

**Comment by amir-zeldes** [comment]
Thanks - there are a couple of new books, all based on the CoptOT book designations. I think the Epistle of Jeremiah is a separate work not included in all canons, see https://en.wikipedia.org/wiki/Letter_of_Jeremiah

**Comment by ctschroeder** [comment]
Ah ok. Obv I did not look closely. Let me check the abbreviations in the urns.

**Comment by ctschroeder** [comment]
@amir-zeldes do you have a table you use to produce the urns?  Looks like some of them may need adjusting.  Letter of Jeremiah docs have the same abbreviation and urns as Jeremiah.  (Abbreviation for the former is usually Ep Jer according to SBL.)  I'm not seeing anything else needing changing at a glance, but if you have a table I can look at, it would probably be more effective than trying to spot-check docs.  Thanks!

**Comment by amir-zeldes** [comment]
Actually that was just a bug of Jeremiah overwriting the similar urn key from Epistle- I'll fix that. Here's the mapping, I think it was supposed to SBL where I got it from:

```
urn_dict={
"Genesis":"gen",
"Exodus":"exod",
"Leviticus":"lev",
"Numbers":"num",
"Deuteronomy":"deut",
"Joshua":"josh",
"Judges": "judg",
"Ruth":"ruth",
"I Samuel": "1sam",
"II Samuel": "2sam",
"I Kings": "1kgs",
"II Kings": "2kgs",
"Job": "job",
"Proverbs": "prov",
"Psalms":"pss",
"Ecclesiastes":"eccl",
"Song of Solomon":"song",
"Isaiah":"isa",
"Jeremiah":"jer",
"Lamentations":"lam",
"Ezekiel":"ezek",
"Daniel":"dan",
"Hosea":"hos",
"Amos":"amos",
"Joel":"joel",
"Obadia":"obad",
"Jonah":"jonah",
"Micah":"mic",
"Nahum":"nah",
"Habakkuk":"hab",
"Zephaniah":"zeph",
"Haggai":"hag",
"Zechariah":"zech",
"Tobit":"tob",
"Baruch":"bar",
"I Esdras": "1esd",
"I Maccabees":"1macc",
"II Maccabees":"2macc",
"III Maccabees":"3macc",
"IV Maccabees":"4macc",
"Prayer of Manasses":"prman",
"Prayer of Azariah":"prazar",
"Bel and the Dragon":"bel",
"Susanna":"sus",
"Wisdom":"wis",
"Sirach":"sir",
"Epistle of Jeremiah":"epjer",
"Judith": "jdt"
}
```

**Comment by ctschroeder** [comment]
Ok thanks!  Looks good!
