### ISSUE TITLE
Correct the lemmas of the suffix conjug verboid, ounte

### ISSUE THREAD

**Issue by lancealanmartin** [CopticScriptorium/corpora#31]
The lemmas of ⲟⲩⲛⲧⲉ are mostly incorrect in the existing corpora. Most examples list the pre-prepositional form ⲟⲩⲛⲧⲁ= as the lemma. Amir has updated the lemmatizer but the older corpora will need to be corrected.

See Annis search: https://corpling.uis.georgetown.edu/annis/scriptorium#_q=bm9ybT0vLuKyqeKym-Kypy4qLyBfPV8gcG9zPSJFWElTVCIgXz1fIGxlbW1h&_c=YXBvcGh0aGVnbWF0YS5wYXRydW0sYmVzYS5sZXR0ZXJzLGpvaGFubmVzLmNhbm9ucyxtYXJ0eXJkb20udmljdG9yLHBzZXVkby50aGVvcGhpbHVzLHNhaGlkaWNhLjFjb3JpbnRoaWFucyxzYWhpZGljYS5tYXJrLHNoZW5vdXRlLmEyMixzaGVub3V0ZS5hYnJhaGFtLHNoZW5vdXRlLmRpcnQsc2hlbm91dGUuZWFnZXJuZXNzLHNoZW5vdXRlLmZveA&cl=5&cr=5&s=0&l=10&_seg=bm9ybV9ncm91cA

**Comment by ctschroeder** [comment]
fixed in published docs of AP corpus 18 September 2019

**Comment by ctschroeder** [comment]
fixed in published Besa letters 18 September 2019

**Comment by ctschroeder** [comment]
- [ ] 60224966	ⲟⲩⲛ̄ ⲧⲁ	root	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	Apa Johannes Canons: MONB.FA [37]-42

- [ ] 60225366	ⲟⲩⲛ̄ ⲧⲁ	root	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	Apa Johannes Canons: MONB.FA [37]-42
- [ ] 59593025	ⲟⲩⲛⲧⲁ	parataxis	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians Chapter 2
- [ ] 59597682	ⲟⲩⲛⲧⲏ	root	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲏ	EXIST	1 Corinthians Chapter 4
- [ ] 59600311	ⲟⲩⲛⲧ	advcl	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧ	EXIST	1 Corinthians Chapter 6
- [ ] 59600665	ⲟⲩⲛⲧⲏ	advcl	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲏ	EXIST	1 Corinthians Chapter 6
- [ ] 59601027	ⲟⲩⲛⲧⲏ	csubj	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲏ	EXIST	1 Corinthians Chapter 6
- [ ] 59603635	ⲟⲩⲛⲧⲉ	aux	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲉ	EXIST	1 Corinthians Chapter 7
- [ ] 59604251	ⲩⲛⲧⲁ	advcl	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians Chapter 7
- [ ] 59604366	ⲩⲛⲧⲁ	acl	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians Chapter 7
- [ ] 59606421	ⲩⲛⲧ	acl	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧ	EXIST	1 Corinthians Chapter 7
- [ ] 59607607	ⲟⲩⲛⲧ	parataxis	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧ	EXIST	1 Corinthians Chapter 7
- [ ] 59608082	ⲟⲩⲛⲧⲁ	ccomp	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians Chapter 7
- [ ] 59608167	ⲟⲩⲛⲧⲁ	advcl	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians Chapter 8
- [ ] 59609295	ⲟⲩⲛⲧⲁ	acl	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians Chapter 8
- [ ] 59611761	ⲟⲩⲛⲧⲁ	parataxis	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians Chapter 9
- [ ] 59622279	ⲟⲩⲛⲧ	acl	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧ	EXIST	1 Corinthians 12
- [ ] 59623675	ⲟⲩⲛⲧⲁ	parataxis	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians 12
- [ ] 59624459	ⲟⲩⲛⲧⲁ	root	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians 12
- [ ] 59624840	ⲟⲩⲛⲧⲁ	advcl	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians 13
- [ ] 59624928	ⲩⲛⲧⲁ	ccomp	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians 13
- [ ] 59629622	ⲟⲩⲛⲧⲁ	parataxis	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians 14
- [ ] 59629647	ⲟⲩⲛⲧⲁ	parataxis	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians 14
- [ ] 59629671	ⲟⲩⲛⲧⲁ	parataxis	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians 14
- [ ] 59629701	ⲟⲩⲛⲧⲁ	advmod	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians 14
- [ ] 59629725	ⲟⲩⲛⲧⲁ	mark	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians 14
- [ ] 59634549	ⲩⲛⲧⲁ	acl	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	1 Corinthians 15
- [ ] 59509395	ⲟⲩⲛⲧ	ccomp	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧ	EXIST	Mark Chapter 2
- [ ] 59531061	ⲟⲩⲛⲧⲏ	root	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲏ	EXIST	Mark Chapter 6
- [ ] 59538176	ⲟⲩⲛⲧⲏ	ccomp	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲏ	EXIST	Mark Chapter 8
- [ ] 59550866	ⲩⲛⲧⲁ	aux	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	Mark Chapter 10
- [ ] 59565536	ⲩⲛⲧⲁ	advcl	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	Mark Chapter 12
- [ ] 59499268	ⲟⲩⲛ̄ⲧⲁ	conj	ⲟⲩⲛⲧⲁ	ⲟⲩⲛⲧⲁ	EXIST	Abraham Our Father: ZH fragments 1a-d
- [ ] 43764102	ⲟⲩⲛ̄ ⲧⲁ	'NULL'	'NULL'	ⲟⲩⲛⲧⲁ	'NULL'	43764104	ⲟⲩⲛ̄ ⲧⲁ	EXIST	43764101	ⲟⲩⲛ̄ ⲧⲁ	ⲟⲩⲛⲧⲁ	I See Your Eagerness: GL 54-60
- [ ] 43815828	ⲟⲩ ⲛ̄ⲧⲁ	'NULL'	'NULL'	ⲟⲩⲛⲧⲁ	'NULL'	43815830	ⲟⲩ ⲛ̄ⲧⲁ	EXIST	43815827	ⲟⲩ ⲛ̄ⲧⲁ	ⲟⲩⲛⲧⲁ	I See Your Eagerness: XJ 65-76
- [ ] 43817640	ⲟⲩⲛⲧ︤	'NULL'	'NULL'	ⲟⲩⲛⲧ	'NULL'	43817642	ⲟⲩⲛⲧ︤	EXIST	43817639	ⲟⲩⲛⲧ︤	ⲟⲩⲛⲧⲁ	I See Your Eagerness: XJ 65-76
- [ ] 43818976	ⲟⲩⲛ̄ ⲧ	'NULL'	'NULL'	ⲟⲩⲛⲧ	'NULL'	43818978	ⲟⲩⲛ̄ ⲧ	EXIST	43818975	ⲟⲩⲛ̄ ⲧ	ⲟⲩⲛⲧⲁ	I See Your Eagerness: XJ 65-76
- [ ]
