### ISSUE TITLE
`copticLit.` instead of `copticLit:` in URN for Onnophrius 4

### ISSUE THREAD

**Issue by lgessler** [CopticScriptorium/corpora#47]
TT markup for [Onnophrius 4](https://github.com/CopticScriptorium/corpora/blob/master/life-onnophrius/life.onnophrius_TT/life.onnophrius.04.tt) has `urn:cts:copticLit.lives.onnophrius.budge:25-33` instead of what I think is the correct `urn:cts:copticLit:lives.onnophrius.budge:25-33`

**Comment by amir-zeldes** [comment]
Oh, that's really weird since none of the other documents have the issue. Someone must have clicked in the field and edited accidentally. 

Fixed in GD, should propagate in next release.
