### ISSUE TITLE
Mark and 1 Cor metadata updates

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/corpora#5]
I noticed some continued metadata inconsistencies in Mark when I checked the URN resolver today.  I went in and fixed them; at the same time, I added a redundant=no metadatum to the Mark and 1 Cor copora files.  (Did not for Sahidica -- that seems a complex question for that corpus, since the Mark and 1 Cor chapters in it are redundant with the manually edited ones.  Didn't know how you wanted to handle it so left it alone.)
@amir-zeldes you should be able to republish and re-TEI/PAULA the Mark and 1Cor corpora now.

**Comment by amir-zeldes** [comment]
1Cor and Mark are republished. Added Greek to analytic view as discussed, let me know what you think. I agree we should talk about the redundant issue and the big NT corpus before republishing.
