### ISSUE TITLE
Wrong title metadatum for shenoute.those.GF311-314.tt

### ISSUE THREAD

**Issue by lgessler** [CopticScriptorium/corpora#76]
From the filename [shenoute.those.GF311-314.tt](https://github.com/CopticScriptorium/corpora/blob/master/shenoute-those/shenoute.those_TT/shenoute.those.GF311-314.tt), I think the title metadatum ought to be `God Says Through Those Who Are His: GF 311-314`, but it is actually `God Says Through Those Who Are His: GF 307-310`. 

The title `God Says Through Those Who Are His: GF 307-310` also exists in [shenoute.those.GF307-310.tt](https://github.com/CopticScriptorium/corpora/blob/master/shenoute-those/shenoute.those_TT/shenoute.those.GF307-310.tt). 

The exact duplication of the title causes an error when browsing to either one of these documents at the moment, since it assumes that titles are unique. So this corpus should be re-imported when the issue is corrected.

**Comment by ctschroeder** [comment]
OOPS. Thanks for the catch! Fixed in Gitdox for next release

**Comment by ctschroeder** [comment]
should be integrated in next release of [shenoute.those](https://github.com/CopticScriptorium/shenoute-discourses5-dev/issues/50)
