### ISSUE TITLE
License of coptic.treebank.conll10

### ISSUE THREAD

**Issue by reckart** [CopticScriptorium/corpora#8]
What is the license of this file? There is no LICENSE file in the respective folder and the license information on the root of the repo is rather vague.

**Comment by ctschroeder** [comment]
@reckart sorry for the delay -- for some reason I didn't see this issue when you created it.  Thanks for your interest!  Licensing information is in the Readme file for this repository, and usually more specific information is in the metadata of the files. Thanks for alerting us to the missing license in this dataset.  
The treebank annotation data is licensed CC-BY 4.0.
@amir-zeldes can you add the license to the documentation and to the data file?  Thanks!!!

**Comment by amir-zeldes** [comment]
Hi @reckart and apologies from me too for the delay. This repo is the CopticScriptorium working directory with just the raw treebank that we are extending. Probably the best place to get the 'official release' from is the UD repo here, which contains the specific licensing information:

https://github.com/UniversalDependencies/UD_Coptic

Files there are in conllu format and split into train/dev/test like other UD projects. However this repo is where the material will appear first before it is split in each version, and is also publicly available, so there's no reason the license shouldn't appear here too. I'm copying over the same license file. Thanks!
